### ISSUE TITLE
/ 누르면 추가팝업 뜨기

### ISSUE THREAD

**Issue by minjeongHEO** [NotionTeam02/fe-notion#94]
#### 상황
<img src="https://github.com/NotionTeam02/fe-notion/assets/96780693/a1db589d-d639-45a1-b9da-b1cb38f86dee"/>
키보드의 '/'  버튼을 누르면 '+' 옵션 버튼을 눌렀을 때의 팝업이 떠야합니다.

`EditableBlock.tsx`에서 + 아이콘을 클릭하기 위한 useRef(plusIconRef) 를 만들어줍니다.

`EditableBlcok.tsx`에서 onKeyUp으로 전달해주는 handleInput 함수를 
```js
const handleInputWrapper = (props: { e: React.KeyboardEvent<HTMLElement>; index: number }) => {
    if (props.e.key === '/') {
      plusIconRef.current?.click();
      return;
    }
    handleInput(props);
  };
```
handleInputWrapper 함수를 새로 만들어서 넘겨줍니다.
이 때 누른 key가 '/' 일 때 plusIconRef를 클릭하도록 하였습니다.

plusIconRef는 `BlockTag.tsx`의 + 옵션 버튼 부분에 ref를 주었습니다.

🚨 하지만, 

- '+' 옵션 버튼을 눌렀을 때의 이벤트는 새 블럭이 하나 추가가 되고, 팝업의 위치가 좀 아래로 내려가야하고,(#101)
- '/' key 를 눌렀을 때는 새 블럭이 추가가 되지 않으며, 팝업의 위치는 아래로 내려가지 않아야 합니다.

**💡 useRef + useEffect + addEventListener**

`blockTag.tsx`에서 마지막 key이벤트의 값이 Enter인지, '/'인지 구분하기 위한 useRef(eventRef)를 만들어줍니다.

useEffect로 `EditableBlock.tsx`에서 전달받은 useRef(contentTagRef)에 'keyup' eventListener를 붙여줍니다.
그리고 그 콜백 함수에서 생성한 eventRef 에 이벤트를 저장합니다.

이 저장된 값으로 +팝업을 띄우는 함수를 실행할 때
값이 '/'이면 return 시켜, 
Enter 이벤트를 실행시키지 않도록 합니다.
그 전에  eventRef에 '/'값이 남아있으므로, eventRef.current = null;  로 값을 비워줍니다.
그렇지 않으면 Enter이벤트를 실행시켜야 할 때도 실행되지 않는 상황이 발생합니다.

isSlash라는 state<boolean>를 하나 생성하여 팝업(`AddPopup.tsx`)에 전달해주고
이 값을 통해 팝업의 위치를 조정합니다. 

<br><br>

## ✅ TODO
- [x] '/' 누르면 추가 팝업만 띄우기
- [x] 새 블럭 생성은 안함
- [x] 팝업 위치 조정

<br><br>
